services:
  broker:
    build:
      context: ./broker-service
    ports:
      - "8080:8080"
    depends_on:
      - authentication
    restart: always

  authentication:
    build:
      context: ./authentication-service
    ports:
      - "8081:8080"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable connect_timeout=5"
    depends_on:
      - postgres

  postgres:
    image: postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: